services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-stocks}
    ports:
      - "5432:5432"
    volumes:
      - stocks_db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-stocks}
      FLASK_ENV: development
      DBT_PROFILES_DIR: /app
      DB_HOST: db
      FRONTEND_URL: http://frontend:3000
      REVALIDATION_SECRET: ${REVALIDATION_SECRET:-super-secret-token}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./stocks-frontend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-stocks}
      REVALIDATION_SECRET: ${REVALIDATION_SECRET:-super-secret-token}
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  stocks_db_data:
